# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_imports = true
# Consistency
newline_style = "Unix"
# Format comments
comment_width = 100
wrap_comments = true
# Errors
error_on_line_overflow = true
error_on_unformatted = true
# For explicit running of rustfmt
edition = "2021"
